apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: users-api
  description: Manages user profiles and accounts
spec:
  type: openapi
  lifecycle: production
  owner: team-auth
  definition: |
    openapi: 3.0.0
    info:
      title: Users API
      version: 1.0.0
    paths:
      /users:
        get:
          summary: Get user list
          responses:
            '200':
              description: OK
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: auth-api
  description: Handles authentication tokens
spec:
  type: openapi
  lifecycle: stable
  owner: team-auth
  definition: |
    openapi: 3.0.0
    info:
      title: Auth API
      version: 1.0.0
    paths:
      /login:
        post:
          summary: Login user
          responses:
            '200':
              description: OK
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: billing-api
  description: REST API for billing and invoices
spec:
  type: openapi
  lifecycle: production
  owner: finance-team
  definition: |
    openapi: 3.0.0
    info:
      title: Billing API
      version: 1.0.0
    paths:
      /invoices:
        get:
          summary: Fetch invoices
          responses:
            '200':
              description: OK
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: notifications-api
  description: Sends in-app and email notifications
spec:
  type: asyncapi
  lifecycle: experimental
  owner: comms-team
  definition: |
    asyncapi: '2.0.0'
    info:
      title: Notifications API
      version: '1.0.0'
    channels:
      user.notifications:
        subscribe:
          summary: Receive notifications
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: payments-api
  description: Payment gateway integration API
spec:
  type: openapi
  lifecycle: production
  owner: payments-team
  definition: |
    openapi: 3.0.0
    info:
      title: Payments API
      version: 1.0.0
    paths:
      /payments:
        post:
          summary: Make a payment
          responses:
            '201':
              description: Created
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: graphql-profile-api
  description: GraphQL API for user profiles
spec:
  type: graphql
  lifecycle: beta
  owner: team-ux
  definition: |
    type Query {
      profile(id: ID!): UserProfile
    }

    type UserProfile {
      id: ID!
      name: String
      email: String
    }
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: grpc-recommendations-api
  description: gRPC API for product recommendations
spec:
  type: grpc
  lifecycle: experimental
  owner: data-science-team
  definition: proto

